// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Tvf0nVcdx8OCEyF-6ABDFzP7dzd-oT4',
    appId: '1:615901094789:web:1e7d275bba502d98a31aec',
    messagingSenderId: '615901094789',
    projectId: 'smartprepquizapp',
    authDomain: 'smartprepquizapp.firebaseapp.com',
    databaseURL: 'https://smartprepquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'smartprepquizapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC10FxeuNVR-pGGJQlKoZxT24phxlRy0Q',
    appId: '1:615901094789:android:c6213f401ad3d95da31aec',
    messagingSenderId: '615901094789',
    projectId: 'smartprepquizapp',
    databaseURL: 'https://smartprepquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'smartprepquizapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqyyQoHdoR1FFDFEouJd-mwob6Hm3EnE4',
    appId: '1:615901094789:ios:16dfaea349b1b0bca31aec',
    messagingSenderId: '615901094789',
    projectId: 'smartprepquizapp',
    databaseURL: 'https://smartprepquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'smartprepquizapp.firebasestorage.app',
    iosClientId: '615901094789-qg7sm232714uu3aoe25piuo8tjj2ejdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqyyQoHdoR1FFDFEouJd-mwob6Hm3EnE4',
    appId: '1:615901094789:ios:16dfaea349b1b0bca31aec',
    messagingSenderId: '615901094789',
    projectId: 'smartprepquizapp',
    databaseURL: 'https://smartprepquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'smartprepquizapp.firebasestorage.app',
    iosClientId: '615901094789-qg7sm232714uu3aoe25piuo8tjj2ejdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Tvf0nVcdx8OCEyF-6ABDFzP7dzd-oT4',
    appId: '1:615901094789:web:4ac236a1d4981715a31aec',
    messagingSenderId: '615901094789',
    projectId: 'smartprepquizapp',
    authDomain: 'smartprepquizapp.firebaseapp.com',
    databaseURL: 'https://smartprepquizapp-default-rtdb.firebaseio.com',
    storageBucket: 'smartprepquizapp.firebasestorage.app',
  );
}
